### PR TITLE
Make it usable in main process

### PR DESCRIPTION
**Pull request by anothertempore**
Hi there,

This PR is for making it usable in main process, the current implementation is unable to work because `--user-data-dir=` is not exist in main process.

My changes are in `resolveUserAppDataPath` function:

```diff
function resolveUserAppDataPath() {
+  const userDataPath = app?.getPath("userData");
+  if (userDataPath) {
+    return userDataPath;
+  }

  const arg = process.argv.find((arg) => arg.startsWith("--user-data-dir="));
  if (!arg) {
    throw new Error(
      "Unable to find --user-data-dir with valid path in process.argv"
    );
  }
  
  ...
}
```

P.S The code in the diff view is a bit messy because we have lint conflict, let me know if you accept the idea and I will proceed to cleanup my code and help setup ESLint as well!

Thanks!

### CODE REVIEW

**Comment by cawa-93** [comment]
Thanks for your PR. I already described how use this in Main
https://github.com/cawa-93/electron-nano-store#in-main

It may be a little tricky but I would like to avoid a confusing mix of contexts. At least for now.

Is there any case not covered by described in doc method?

**Comment by anothertempore** [comment]
Thanks for your response. I've tried but seems like there has a bug:

Here is my code:

```
defineStore<StoreData>(resolveStoreFilepath('test', app.getPath('userData')))
```

Here is the error:

image

Here is the bug:

https://github.com/cawa-93/electron-nano-store/blob/main/src/index.ts#L42

There is using `basename(storeName)` to compare with `storeName`. In my case, `basename(storeName)` is `test.nano-store.json` while `storeName` is the full path.

---

Also I'm wondering what's your thoughts behind this design? From my point of view, my instincts idea is using the same API for different secnarios.

Thanks and happy holiday :)

**Comment by cawa-93** [comment]
You probably import defineStore from wrong package.

**Comment by anothertempore** [comment]
Eh, here is my full of code:

```typescript
import {app} from 'electron';
import {defineStore, resolveStoreFilepath} from 'electron-nano-store';
import {basename} from 'path';
import type {StoreData} from './type';

const storeName = resolveStoreFilepath('test', app.getPath('userData'));
console.log(storeName); // /Users/kexin.li/Library/Application Support/queryqueen/test.nano-store.json

console.log(basename(storeName)); // test.nano-store.json

defineStore<StoreData>(storeName);

// basename(storeName) !== storeName
```

I'm using electron-nano-store v0.3.0

---

In preload script, the usage is:

```typescript
import {defineStore, resolveStoreFilepath} from 'electron-nano-store';
import {basename} from 'path';

defineStore<StoreData>('store')

// basename('store') === 'store'
```

**Comment by cawa-93** [comment]
Yeap. Wrong one. Check the docs again. In Main you should use directly fs-nano-store.

**Comment by anothertempore** [comment]
Understood, thanks.

**Pull request closed without merging**
